ASCII Schedule Formatter
CSC207-UofT/course-project-tut0201-007 pull request #61
Opened 2021-11-26 01:52 UTC by EclipseIsDead

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please cite/describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A

# Does this PR follow the rubric?

Please describe any SOLID principle, design pattern, etc. used in the PR that will be added to the design document.

# Checklist:

- [ ] I ran `./gradlew spotlessApply`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I ran `./gradlew build` and the gradle build succeeded
- [ ] I have not violated any design principles

# Other Comments:

Other comments that should be made clear.

2021-11-30 01:29 UTC, sugolov commented on src/main/java/entities/ASCIIFormatter.java
> +            output.append(String.format(leftAlignFormat, "PogU" + i, i * i));
what does "PogU" do lol

2021-12-05 23:09 UTC, EclipseIsDead commented on src/main/java/entities/ASCIIFormatter.java
> +            output.append(String.format(leftAlignFormat, "PogU" + i, i * i));
temp holder for da string

2021-12-07 02:51 UTC, EclipseIsDead commented
Yo what's up with `SchedulerTest`?

2021-12-07 16:12 UTC, sugolov requested changes
overall looks good. please add course names to the schedule slots though. also, how does the ascii handle schedules with conflicts?

2021-12-07 19:17 UTC, kenneth-miura requested changes
1 typo in docs, but besides that looks great

2021-12-07 19:17 UTC, kenneth-miura commented on src/main/java/entities/ASCIIFormatter.java
> +     * @return list of Booleans (0 is for F, 1 is for F)
I'm assuming 1 is for S lol

2021-12-07 19:18 UTC, EclipseIsDead commented on src/main/java/entities/ASCIIFormatter.java
> +     * @return list of Booleans (0 is for F, 1 is for F)
lol

2021-12-07 22:52 UTC, merged