CSVExporter/Importer
CSC207-UofT/course-project-tut0201-007 pull request #62
Opened 2021-11-26 18:50 UTC by roryhofland

# Description

Worker classes to import/export a schedule in a CSV file format.

## Type of change

Please delete options that are not relevant.

- [ ] New feature 
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please cite/describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Pending

# Does this PR follow the rubric?

Yes

Please describe any SOLID principle, design pattern, etc. used in the PR that will be added to the design document. If it does, **please link in design doc!!!**

Template method (already linked)

# Checklist:

- [ ] I ran `./gradlew spotlessApply`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I ran `./gradlew build` and the gradle build succeeded
- [ ] I have not violated any design principles

# Other Comments:

Other comments that should be made clear.

2021-11-27 19:58 UTC, roryhofland commented on src/main/java/workers/CSVExporter.java
> +    private int num = 0;
Could be added to the Exporter superclass.

2021-11-27 20:04 UTC, roryhofland commented on src/main/java/workers/CSVExporter.java
> +    private final LocalDate WINTER_SEMESTER_END_DATE = LocalDate.of(endYear, 4, 11);
These could be added to superclass.

2021-11-29 15:32 UTC, kenneth-miura requested changes
Sorry for late review, was getting rocked by csc258. Looks good in general, I have one point about the arguments for `outputSchedule`.

2021-11-29 15:32 UTC, kenneth-miura commented on src/main/java/workers/CSVExporter.java
> +    private final LocalDate WINTER_SEMESTER_END_DATE = LocalDate.of(endYear, 4, 11);
yeah you're right

2021-11-29 22:56 UTC, roryhofland commented on src/main/java/controllers/CommandLineInterface.java
> +                case 'C':
yeah pretty much. for actual calendar stuff .ics is better.

2021-11-30 01:17 UTC, sugolov commented
Looks good to me, very nice

2021-11-30 18:22 UTC, merged