RateMyProfessor Web Scraping + Filter
CSC207-UofT/course-project-tut0201-007 pull request #71
Opened 2021-11-29 20:32 UTC by BakerWJ

# Description

Implements JSoup to scrape RateMyProfessor to assess the quality of the profs in each section. This score is then used by the RMPFilter, which can enforce a minimum allowed score for a professor.

## Type of change

- [ ] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# How Has This Been Tested?

No tests added yet, but I have changed the timeout of certain tests to make sure that they still pass, even though the scraper is being used.

# Does this PR follow the rubric?

No design patterns used.

# Checklist:

- [ ] I ran `./gradlew spotlessApply`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I ran `./gradlew build` and the gradle build succeeded
- [ ] I have not violated any design principles

# Other Comments:

Other comments that should be made clear.

2021-12-04 15:10 UTC, kenneth-miura requested changes
looks good. How much does running the RateMyProfessor webscraping for every section affect runtime? Is it noticeable when u run through CLI?

2021-12-04 15:10 UTC, kenneth-miura commented on src/main/java/workers/ProfessorRatingScraper.java
> +    public static double getRating(String firstName, String lastName) {
chris wants us to use static less to show we understand OOP. Can you refactor this so it's not static?

2021-12-05 17:07 UTC, EclipseIsDead requested changes
Good stuff, 2 things:
- Add tests. If you don't want to/can't then I will just lmk
- Why did you need to increase the timeouts for tests

2021-12-05 17:07 UTC, EclipseIsDead commented on src/main/java/workers/ProfessorRatingScraper.java
> +            return 2.5;
This is a big no no, throw the error. I see that we need a return but you could refactor it to just throw the error instead w/out having to return 2.5. Up to you, at the very least throw the error.

2021-12-05 17:07 UTC, EclipseIsDead commented on src/test/java/filtersTests/CourseExclusionFilterTest.java
> +    @Test(timeout = 5000)
Why did our runtimes like triple?

2021-12-06 23:28 UTC, merged