Export img
CSC207-UofT/course-project-tut0201-007 pull request #78
Opened 2021-12-05 21:33 UTC by kenneth-miura

# Description

Allows you to export to jpg. If both fall and winter session in schedule, generates two jpgs

![image](https://user-images.githubusercontent.com/22108651/144759191-b80de2f8-0dde-4c33-ac9d-03d4558923f4.png)

Fixes # (issue) 

## Type of change

- [x] New feature 

# How Has This Been Tested?
Manual tests

# Checklist:

- [x] I ran `./gradlew spotlessApply`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I ran `./gradlew build` and the gradle build succeeded
- [x] I have not violated any design principles

# Other Comments:

Other comments that should be made clear.

2021-12-05 21:34 UTC, kenneth-miura commented
I can add tests for the exporter, in terms of verifying it'll only create a winter schedule if the generated schedule has winter courses, and same for fall. Is that worth it?

2021-12-05 23:15 UTC, roryhofland approved these changes
I really like this, and I think Chris will too. I tried it with my classes this semester and it gave me my exact timetable.

2021-12-06 02:57 UTC, lorena-b requested changes

2021-12-06 02:57 UTC, lorena-b commented on src/main/java/controllers/CommandLineInterface.java
> +                            "Please specify the name you'd like to save this Schedule under.");
make this WHITE_BOLD

2021-12-06 02:57 UTC, lorena-b commented on src/main/java/controllers/CommandLineInterface.java
> +                    System.out.printf("Saving this schedule in .jpg format...");
green

2021-12-06 03:00 UTC, lorena-b commented
I think this looks really good! Adding tests for the exporter would be good because it will get the coverage up

2021-12-06 03:03 UTC, lorena-b commented on src/main/java/workers/ImageExporter.java
> +    }
was this for demo purposes?

2021-12-06 04:32 UTC, kenneth-miura commented
ok im going to add tests in a separate PR later, want to get this merged in for demo mon

2021-12-06 04:33 UTC, merged